/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.Persona.EstudianteController;
import controlador.tda.lista.ListaEnlazada;
import controlador.tda.lista.ListaEnlazadaServices;
import controlador.utiles.TipoOrdenacion;
import static java.lang.Math.E;
import static java.lang.StrictMath.E;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Estudiante;
import vista.ModeloTablas.TablaEstudiantes;

/**
 *
 * @author Gigabyte
 */
public class Frm_Principal extends javax.swing.JDialog {

    private TablaEstudiantes tp = new TablaEstudiantes();
    private EstudianteController pc = new EstudianteController();

    /**
     * Creates new form Frm_Ordenamiento
     */
    public Frm_Principal(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        cargarTabla();
    }

    public void cargarTabla() {
        tp.setLista(pc.listar());
        tblPersona.setModel(tp);
        tblPersona.updateUI();
    }

    public void limpiar() {
        jTNombre.setText(" ");
        jTApellidos.setText(" ");
        jTCedula.setText(" ");
        jTNota.setText(" ");
        jTDato.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxMetodoOrdenacion = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        cbxOrdenOrdenamiento = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        cbxAtributo = new javax.swing.JComboBox<String>();
        btnFiltrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersona = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTDato = new javax.swing.JTextField();
        cbxAtributo1 = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelTime = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTApellidos = new javax.swing.JTextField();
        jTCedula = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTNota = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manipulación de Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel1.setText("Método de Ordenación:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(11, 28, 134, 26);

        cbxMetodoOrdenacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Shell" }));
        cbxMetodoOrdenacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMetodoOrdenacionActionPerformed(evt);
            }
        });
        jPanel3.add(cbxMetodoOrdenacion);
        cbxMetodoOrdenacion.setBounds(155, 28, 133, 26);

        jLabel2.setText("Orden de Ordenamiento:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(11, 79, 143, 16);

        cbxOrdenOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ascendente", "Descendente" }));
        jPanel3.add(cbxOrdenOrdenamiento);
        cbxOrdenOrdenamiento.setBounds(155, 76, 133, 22);

        jLabel3.setText("Ordenar por:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(318, 28, 75, 26);

        cbxAtributo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nombre", "apellido", "cedula", "notas" }));
        jPanel3.add(cbxAtributo);
        cbxAtributo.setBounds(405, 28, 130, 26);

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnFiltrar);
        btnFiltrar.setBounds(420, 80, 99, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 210, 860, 140);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setLayout(null);

        tblPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPersona);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 630, 240);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Busqueda");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(650, 30, 100, 30);

        jLabel5.setText("Dato:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(660, 160, 31, 16);
        jPanel2.add(jTDato);
        jTDato.setBounds(730, 160, 110, 22);

        cbxAtributo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nombre", "apellido", "telefono", "cedula" }));
        jPanel2.add(cbxAtributo1);
        cbxAtributo1.setBounds(650, 110, 130, 26);

        jLabel6.setText("Busqueda por:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(660, 70, 100, 26);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(690, 210, 71, 25);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 350, 860, 300);
        jPanel1.add(labelTime);
        labelTime.setBounds(20, 510, 530, 30);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso"));
        jPanel4.setLayout(null);

        jLabel7.setText("Nombres:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 40, 60, 16);

        jLabel8.setText("Apellidos:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 80, 60, 16);

        jLabel9.setText("Cedula:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 130, 70, 16);

        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });
        jPanel4.add(jTNombre);
        jTNombre.setBounds(110, 40, 260, 22);

        jTApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidosActionPerformed(evt);
            }
        });
        jPanel4.add(jTApellidos);
        jTApellidos.setBounds(110, 80, 260, 22);

        jTCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCedulaActionPerformed(evt);
            }
        });
        jPanel4.add(jTCedula);
        jTCedula.setBounds(110, 130, 260, 22);

        jLabel10.setText("Nota:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(510, 40, 31, 16);
        jPanel4.add(jTNota);
        jTNota.setBounds(560, 40, 130, 22);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(540, 100, 79, 25);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 10, 860, 190);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 660);

        setSize(new java.awt.Dimension(911, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed

        try {
            ordenarShell();
        } catch (Exception ex) {
            Logger.getLogger(Frm_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            BusquedaBinaria();
            limpiar();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxMetodoOrdenacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMetodoOrdenacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMetodoOrdenacionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        guardar();
        cargarTabla();
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void jTApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidosActionPerformed

    private void jTCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCedulaActionPerformed

    public void guardar() {
        double notas = Double.valueOf(jTNota.getText());
        String estado;
        if (notas >= 7) {
            estado = "Aprovado";
        } else {
            estado = "Reprovado";
        }
        pc.getEstudiante().setNombre(jTNombre.getText());
        pc.getEstudiante().setApellido(jTApellidos.getText());
        pc.getEstudiante().setEstado(estado);
        pc.getEstudiante().setNota(notas);
        pc.getEstudiante().setCedula(jTCedula.getText());
        if (pc.guardar()) {
//                JOptionPane.showMessageDialog(null, "Lista Creada con Exito", "OK", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo crear la Lista", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void ordenarShell() throws Exception {
        ListaEnlazadaServices<Estudiante> listaP = pc.getListaEstudiante();
        long inicio = System.currentTimeMillis();
        listaP.getLista().ordenar_Shell(String.valueOf(cbxAtributo.getSelectedItem()), orden(cbxOrdenOrdenamiento.getSelectedIndex()));
        long fin = System.currentTimeMillis();
        double tiempo = (double) ((fin - inicio) / 1000);
        labelTime.setText("Tiempo de Ordenacion Shell: " + tiempo + " seg");
        tp.setLista(listaP);
        tblPersona.setModel(tp);
        tblPersona.updateUI();
    }

    public void BusquedaBinaria() throws Exception {
        tp.setLista(null);
        tblPersona.setModel(tp);
        tblPersona.updateUI();
        ListaEnlazadaServices<Estudiante> listaP = pc.getListaEstudiante();
        ListaEnlazada<Estudiante> listaA = new ListaEnlazada<>();
        long inicio = System.currentTimeMillis();
        listaP.busquedaBR(listaA, cbxAtributo1.getSelectedItem().toString(), jTDato.getText(), 0, listaP.getSize() - 1);
        long fin = System.currentTimeMillis();
        double tiempo = (double) ((fin - inicio) / 1000);
        labelTime.setText("Tiempo de Busqueda Binaria: " + tiempo + " seg");
        tp.setLista(listaP);
        tblPersona.setModel(tp);
        tblPersona.updateUI();
    }

    public TipoOrdenacion orden(Integer or) {

        TipoOrdenacion ord = null;
        if (or == 0) {
            ord = TipoOrdenacion.DESCENDENTE;
        } else {
            ord = TipoOrdenacion.ASCENDENTE;
        }
        return ord;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Principal dialog = new Frm_Principal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cbxAtributo;
    private javax.swing.JComboBox<String> cbxAtributo1;
    private javax.swing.JComboBox<String> cbxMetodoOrdenacion;
    private javax.swing.JComboBox<String> cbxOrdenOrdenamiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTApellidos;
    private javax.swing.JTextField jTCedula;
    private javax.swing.JTextField jTDato;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTNota;
    private javax.swing.JLabel labelTime;
    private javax.swing.JTable tblPersona;
    // End of variables declaration//GEN-END:variables
}
